services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=5GB'
      - '--web.enable-remote-write-receiver'
      - '--log.level=info'
      - '--query.timeout=2m'
      - '--query.max-concurrency=20'
    restart: unless-stopped

volumes:
  prometheus_data:

