global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.hanz.lol']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node.hanz.lol']

  - job_name: 'phoenix_node_exporter'
    static_configs:
      - targets: ['phoenix.ip.junox.net:9100']

  - job_name: 'alix_nginx_exporter'
    static_configs:
      - targets: ['localhost:9113']
